### PR TITLE
adds license acceptance variable to config

### LINKED ISSUE #39: Habitat license acceptance
Currently there is no way to use habitat versions greater than 0.79.1 due to license acceptance.

### PR DESCRIPTION
**Pull request by skylerto**
Resolves #39 in that you have to opt-in via config to accept the license. 

Signed-off-by: skylerto <skylerclayne@gmail.com>

### CODE REVIEW

**Comment by skylerto** [comment]
Just had a look at the CI, looks to be that some of the infractions are similar to the additions I had made.

Shall I fix _all_, _my changes_, or _none_?

**Comment by skylerto** [comment]
Looks like they were fixed in a PR after this one, updating to to match.

**Comment by skylerto** [comment]
Was wondering if I could get a review on this, maybe from @smurawski or @robbkidd? As you were the last two active here.

**Comment by smurawski** [comment]
@robbkidd, if you have cycles to merge and release, feel free. Otherwise, I'll see if I can get to it tomorrow.

**Comment by skylerto** [comment]
@robbkidd so sorry I didn't get back to you on this! I'm working on the changes  now.

**Comment by robbkidd** [comment]
Rubocooooop! 😠 

Rubocooooop!

**Comment by robbkidd** [comment]
[kitchen-habitat 0.11.2](https://rubygems.org/gems/kitchen-habitat/versions/0.11.2) released to RubyGems.

**Pull request merged**
