### PR TITLE
Updates to support 0.57.0

### LINKED ISSUE #12: supervisor 0.56.0 breaks converge
It appears that the release of 0.56.0 has broken converges. Converging a fresh container results in an infinite loop on the following:

       ✗✗✗
       ✗✗✗ [Err: 1] IoError while reading or writing ctl secret, /hab/sup/default/CTL_SECRET, Permission denied (os error 13)
       ✗✗✗

### PR DESCRIPTION
**Pull request by skylerto**
Updates to support the change in the supervisor/package load options as well as the unload of the package on clean up.

resolves #12 

Signed-off-by: skylerto <skylerclayne@gmail.com>

### CODE REVIEW

**Comment by jkerry** [comment]
LGTM. There's a whitespace style issue on
lib/kitchen/provisioner/habitat.rb:168
but that's in master so I won't hold it against you 😄 
Paging @smurawski

**Comment by skylerto** [comment]
haha thanks!

Thought I might as well clean up some extra spaces in the file. :)

**Comment by epcim** [comment]
I can confirm it works and fixes the bug #12

**Comment by skylerto** [comment]
@smurawski can we get a new release here https://rubygems.org/gems/kitchen-habitat please?

**Comment by smurawski** [comment]
@skylerto - https://rubygems.org/gems/kitchen-habitat/versions/0.8.0

**Pull request merged**
