### PR TITLE
force supervisor to run

### LINKED ISSUE #28: Issue with starting supervisor under nohup
When running kitchen converge I get the following error:

```
[kitchen@95b91cf4607d ~]$ tailf nohup.out
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/hab-launcher/8133/20180810175521
★ Install of core/hab-launcher/8133/20180810175521 complete with 1 new packages installed.
hab-sup(MR): Supervisor Member-ID a51483973986496fa19f8dbe0b20e494
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting ctl-gateway on 127.0.0.1:9632
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
hab-sup(AG): The skylerto/vault/0.10.5/20180817131403 service was successfully loaded
hab-launch(SV): Supervisor process killed by signal 1; shutting everything down now
ERROR 2018-08-20T14:49:14Z: hab_launch: Launcher exiting with code 86
```

This happens consistently.

Using the docker provider, and centos docker image.

This is a confirmed issue on v0.9.0 and v0.10.0.

Confirmed earliest break time was Friday, August 17, 2018.

### PR DESCRIPTION
**Pull request by skylerto**
Would love feedback on this, I realize the solution isn't very elegant but it solves the problem.

resolves #28 

Signed-off-by: skylerto <skylerclayne@gmail.com>

### CODE REVIEW

**Comment by gscho** [comment]
@skylerto If this is a habitat issue, should we just wait for this to be resolved instead of implementing a work around?

**Comment by skylerto** [comment]
I've confirmed it isn't a habitat issue. I've ran the same code with all different versions of the supervisor (0.57.0, 0.58.0, 0.59.0, 0.61.0).

**Comment by skylerto** [comment]
@jkerry

**Comment by jkerry** [comment]
Sorry for the delay in these guys. I don't see anything alarming here but it makes me keenly aware that we don't have any solid integration testing in place.  I'm going to merge and release and keep an eye out for issues.

**Comment by gscho** [comment]
@jkerry 
Created an issue for this.
https://github.com/test-kitchen/kitchen-habitat/issues/31

**Comment by jkerry** [comment]
released in 0.11.0
https://rubygems.org/gems/kitchen-habitat/versions/0.11.0

**Pull request merged**
